[project]
name = "advent-of-code-2024"
version = "0.0.1"
requires-python = ">= 3.12.3, < 3.13.0"

dependencies = [
    "pyright",
    "ruff == 0.7.2",
    "pytest",
    "numpy",
    "pulp>=2.9.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
